name: Bruno API Tests Demo
on: [pull_request, push]

jobs:
  bruno:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Create reports dir
        run: mkdir -p public

      - name: Create .env file
        run: |
          cd collections/demo
          touch .env
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env

      - uses: usebruno/bruno-cli-action@v1
        with:
          working-directory: collections/demo
          command: 'run --env test --reporter-html ../../public/index.html'

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'